"""create execution and recovery tables (2-d)

Revision ID: 235ce4f5c94c
Revises: ced84c31fc05
Create Date: 2026-05-21 21:15:29.102360

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "235ce4f5c94c"
down_revision: str | Sequence[str] | None = "ced84c31fc05"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "failure_reason_tags",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tag_code", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("100"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_failure_reason_tags_tag_code"), "failure_reason_tags", ["tag_code"], unique=True
    )
    op.create_table(
        "recovery_strategy_catalog",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("strategy_code", sa.String(length=64), nullable=False),
        sa.Column(
            "recovery_option_group",
            sa.Enum("DOWNSCOPE", "RESCHEDULE", "CARRY_OVER", "PARK", name="recovery_option_group"),
            nullable=False,
        ),
        sa.Column("if_then_template", sa.Text(), nullable=False),
        sa.Column(
            "default_estimate_minutes", sa.Integer(), server_default=sa.text("5"), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("100"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recovery_strategy_catalog_strategy_code"),
        "recovery_strategy_catalog",
        ["strategy_code"],
        unique=True,
    )
    op.create_table(
        "execution_events",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("action_item_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "actual_start_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actual_end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_duration_minutes", sa.Integer(), nullable=True),
        sa.Column("pause_total_minutes", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("delay_minutes", sa.Integer(), nullable=True),
        sa.Column(
            "completion_status",
            sa.Enum(
                "in_progress",
                "done",
                "partial_done",
                "failed",
                "over_done",
                name="execution_completion_status",
            ),
            server_default="in_progress",
            nullable=False,
        ),
        sa.Column("user_rating", sa.Integer(), nullable=True),
        sa.Column("user_feedback_encrypted", sa.Text(), nullable=True),
        sa.Column("focus_mode_used", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("dnd_used", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["action_item_id"], ["action_items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_execution_events_action_item_id"),
        "execution_events",
        ["action_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_execution_events_user_id"), "execution_events", ["user_id"], unique=False
    )
    op.create_table(
        "context_snapshots",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("execution_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "time_of_day",
            sa.Enum(
                "early_morning",
                "morning",
                "afternoon",
                "evening",
                "night",
                name="context_time_of_day",
            ),
            nullable=False,
        ),
        sa.Column("day_of_week", sa.SmallInteger(), nullable=False),
        sa.Column("calendar_density", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("next_event_gap_minutes", sa.Integer(), nullable=True),
        sa.Column("estimated_energy_level", sa.SmallInteger(), nullable=True),
        sa.Column("focus_level", sa.SmallInteger(), nullable=True),
        sa.Column("overwhelm_level", sa.SmallInteger(), nullable=True),
        sa.Column("noise_level", sa.SmallInteger(), nullable=True),
        sa.Column("interruption_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "location_type",
            sa.Enum(
                "home",
                "cafe",
                "library",
                "school",
                "work",
                "transit",
                "other",
                name="context_location_type",
            ),
            nullable=True,
        ),
        sa.Column(
            "device_type",
            sa.Enum("mobile", "tablet", "desktop", name="context_device_type"),
            nullable=True,
        ),
        sa.Column("weather", sa.String(length=64), nullable=True),
        sa.Column("companion_present", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["execution_event_id"], ["execution_events.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_context_snapshots_execution_event_id"),
        "context_snapshots",
        ["execution_event_id"],
        unique=False,
    )
    op.create_table(
        "execution_failure_tags",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("execution_event_id", sa.UUID(), nullable=False),
        sa.Column("failure_tag_id", sa.UUID(), nullable=False),
        sa.Column("memo_encrypted", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["execution_event_id"], ["execution_events.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["failure_tag_id"], ["failure_reason_tags.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "execution_event_id", "failure_tag_id", name="uq_execution_failure_tags_event_tag"
        ),
    )
    op.create_index(
        op.f("ix_execution_failure_tags_execution_event_id"),
        "execution_failure_tags",
        ["execution_event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_execution_failure_tags_failure_tag_id"),
        "execution_failure_tags",
        ["failure_tag_id"],
        unique=False,
    )
    op.create_table(
        "interruption_events",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("execution_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "interruption_type",
            sa.Enum("user_pause", "system", "forced", name="interruption_type"),
            server_default="user_pause",
            nullable=False,
        ),
        sa.Column(
            "interruption_source",
            sa.Enum(
                "phone",
                "message",
                "person",
                "self_distraction",
                "fatigue",
                "emergency",
                "other",
                name="interruption_source",
            ),
            server_default="other",
            nullable=False,
        ),
        sa.Column("suspended_step", sa.String(length=500), nullable=True),
        sa.Column("resume_delay_minutes", sa.Integer(), nullable=True),
        sa.Column("resumed_after_interrupt", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["execution_event_id"], ["execution_events.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_interruption_events_execution_event_id"),
        "interruption_events",
        ["execution_event_id"],
        unique=False,
    )
    op.create_table(
        "recovery_attempts",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("execution_event_id", sa.UUID(), nullable=False),
        sa.Column("strategy_id", sa.UUID(), nullable=False),
        sa.Column(
            "recovery_option_group",
            sa.Enum("DOWNSCOPE", "RESCHEDULE", "CARRY_OVER", "PARK", name="recovery_option_group"),
            nullable=False,
        ),
        sa.Column("suggested_action_text", sa.Text(), nullable=False),
        sa.Column(
            "user_decision",
            sa.Enum("pending", "accepted", "rejected", "postponed", name="recovery_user_decision"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("recovery_decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resulting_action_item_id", sa.UUID(), nullable=True),
        sa.Column(
            "llm_fallback_used", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("recovery_duration_minutes", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["execution_event_id"], ["execution_events.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["resulting_action_item_id"], ["action_items.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["strategy_id"], ["recovery_strategy_catalog.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recovery_attempts_execution_event_id"),
        "recovery_attempts",
        ["execution_event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recovery_attempts_strategy_id"), "recovery_attempts", ["strategy_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_recovery_attempts_strategy_id"), table_name="recovery_attempts")
    op.drop_index(op.f("ix_recovery_attempts_execution_event_id"), table_name="recovery_attempts")
    op.drop_table("recovery_attempts")
    op.drop_index(
        op.f("ix_interruption_events_execution_event_id"), table_name="interruption_events"
    )
    op.drop_table("interruption_events")
    op.drop_index(
        op.f("ix_execution_failure_tags_failure_tag_id"), table_name="execution_failure_tags"
    )
    op.drop_index(
        op.f("ix_execution_failure_tags_execution_event_id"), table_name="execution_failure_tags"
    )
    op.drop_table("execution_failure_tags")
    op.drop_index(op.f("ix_context_snapshots_execution_event_id"), table_name="context_snapshots")
    op.drop_table("context_snapshots")
    op.drop_index(op.f("ix_execution_events_user_id"), table_name="execution_events")
    op.drop_index(op.f("ix_execution_events_action_item_id"), table_name="execution_events")
    op.drop_table("execution_events")
    op.drop_index(
        op.f("ix_recovery_strategy_catalog_strategy_code"), table_name="recovery_strategy_catalog"
    )
    op.drop_table("recovery_strategy_catalog")
    op.drop_index(op.f("ix_failure_reason_tags_tag_code"), table_name="failure_reason_tags")
    op.drop_table("failure_reason_tags")
    # ### end Alembic commands ###

    # PostgreSQL ENUM 타입 수동 drop (Alembic autogenerate 가 자동 안 함).
    for enum_name in (
        "recovery_user_decision",
        "recovery_option_group",
        "interruption_source",
        "interruption_type",
        "context_device_type",
        "context_location_type",
        "context_time_of_day",
        "execution_completion_status",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
