"""create all tables aligned with DB v0.7.1 (consolidated)

Revision ID: 59acd6c5f086
Revises:
Create Date: 2026-05-21 23:14:27.861623

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "59acd6c5f086"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "failure_reason_tags",
        sa.Column("tag_code", sa.String(length=30), nullable=False),
        sa.Column("label_ko", sa.String(length=60), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("100"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("tag_code"),
    )
    op.create_table(
        "recovery_strategy_catalog",
        sa.Column("strategy_type", sa.String(length=30), nullable=False),
        sa.Column(
            "option_group",
            sa.Enum("DOWNSCOPE", "RESCHEDULE", "CARRY_OVER", "PARK", name="recovery_option_group"),
            nullable=False,
        ),
        sa.Column("label_ko", sa.String(length=60), nullable=False),
        sa.Column("if_then_template", sa.Text(), nullable=False),
        sa.Column(
            "min_recovery_unit_minutes", sa.Integer(), server_default=sa.text("5"), nullable=False
        ),
        sa.Column(
            "primary_trigger_tags",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("allow_rest_mode", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("display_priority", sa.Integer(), server_default=sa.text("100"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("strategy_type"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "onboarding_state",
            sa.Enum(
                "WELCOME",
                "ONBOARDING_INTERVIEW",
                "ONBOARDING_CONFIRM",
                "ONBOARDING_CALENDAR",
                "ONBOARDING_MANUAL_SCHEDULE",
                "ONBOARDING_POLICIES",
                "ONBOARDING_FIRST_PLAN",
                "ONBOARDING_NOTIFICATIONS",
                "ACTIVE",
                name="user_onboarding_state",
            ),
            server_default="WELCOME",
            nullable=False,
        ),
        sa.Column(
            "tone_mode",
            sa.Enum("gentle", "strict", "encouraging", name="user_tone_mode"),
            nullable=True,
        ),
        sa.Column("is_beta", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("is_anonymized", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("timezone", sa.String(length=64), server_default="Asia/Seoul", nullable=False),
        sa.Column(
            "last_active_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("anonymized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("focus_mode_preferences", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "behavioral_profiles",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "time_chunk_preference", sa.String(length=20), server_default="30", nullable=False
        ),
        sa.Column(
            "energy_cycle",
            sa.Enum(
                "morning", "afternoon", "evening", "night", "varies", name="behavioral_energy_cycle"
            ),
            server_default="varies",
            nullable=False,
        ),
        sa.Column("success_buffer", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("preferred_start_time", sa.Time(), nullable=True),
        sa.Column("preferred_end_time", sa.Time(), nullable=True),
        sa.Column("attention_span", sa.Integer(), server_default=sa.text("30"), nullable=False),
        sa.Column("context_switching_cost", sa.Integer(), nullable=True),
        sa.Column(
            "recovery_speed_type",
            sa.Enum("fast", "medium", "slow", name="behavioral_recovery_speed"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "calendar_connections",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum("google", "apple", "samsung", name="calendar_provider"),
            server_default="google",
            nullable=False,
        ),
        sa.Column("access_token_encrypted", sa.Text(), nullable=False),
        sa.Column("refresh_token_encrypted", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scopes", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "fixed_schedules",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("days_of_week", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_fixed_schedules_user_id"), "fixed_schedules", ["user_id"], unique=False
    )
    op.create_table(
        "goals",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "study",
                "project",
                "health",
                "routine",
                "schedule",
                "career",
                "relationship",
                "self_dev",
                "other",
                name="goal_category",
            ),
            server_default="other",
            nullable=False,
        ),
        sa.Column(
            "goal_tier",
            sa.Enum("focus", "maintain", "parked", name="goal_tier"),
            server_default="maintain",
            nullable=False,
        ),
        sa.Column("deadline", sa.Date(), nullable=True),
        sa.Column("priority_level", sa.Integer(), server_default=sa.text("3"), nullable=False),
        sa.Column("estimated_minutes", sa.Integer(), nullable=True),
        sa.Column("week_tier_key", sa.String(length=20), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "archived", "completed", name="goal_status"),
            server_default="active",
            nullable=False,
        ),
        sa.Column("why_now", sa.Text(), nullable=True),
        sa.Column("first_step", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_goals_user_id"), "goals", ["user_id"], unique=False)
    op.create_table(
        "habits",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "study",
                "health",
                "routine",
                "self_dev",
                "relationship",
                "other",
                name="habit_category",
            ),
            server_default="other",
            nullable=False,
        ),
        sa.Column("frequency_per_week", sa.Integer(), server_default=sa.text("3"), nullable=False),
        sa.Column("target_count", sa.Integer(), server_default=sa.text("3"), nullable=False),
        sa.Column(
            "minutes_per_session", sa.Integer(), server_default=sa.text("30"), nullable=False
        ),
        sa.Column(
            "time_preference",
            sa.Enum("morning", "afternoon", "evening", "anytime", name="habit_time_preference"),
            server_default="anytime",
            nullable=False,
        ),
        sa.Column("priority_level", sa.Integer(), server_default=sa.text("3"), nullable=False),
        sa.Column(
            "consecutive_miss_weeks", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("last_penalty_evaluated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "last_penalty_decision",
            sa.Enum("accepted", "rejected", name="habit_penalty_decision"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("frequency_per_week BETWEEN 1 AND 7", name="ck_habit_frequency_range"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_habits_user_id"), "habits", ["user_id"], unique=False)
    op.create_table(
        "idempotency_keys",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("endpoint", sa.String(length=128), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("request_body_hash", sa.String(length=64), nullable=False),
        sa.Column("response_cache", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "endpoint", "key", name="uq_idempotency_keys_user_endpoint_key"
        ),
    )
    op.create_index(
        op.f("ix_idempotency_keys_expires_at"), "idempotency_keys", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_idempotency_keys_user_id"), "idempotency_keys", ["user_id"], unique=False
    )
    op.create_table(
        "interaction_styles",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "suggestion_style",
            sa.Enum("soft", "neutral", "firm", name="interaction_suggestion_style"),
            server_default="neutral",
            nullable=False,
        ),
        sa.Column(
            "recovery_tone",
            sa.Enum("gentle", "normal", "encouraging", name="interaction_recovery_tone"),
            server_default="normal",
            nullable=False,
        ),
        sa.Column(
            "explanation_depth",
            sa.Enum("brief", "normal", "detailed", name="interaction_explanation_depth"),
            server_default="normal",
            nullable=False,
        ),
        sa.Column(
            "reminder_frequency",
            sa.Enum("minimal", "standard", "active", name="interaction_reminder_frequency"),
            server_default="standard",
            nullable=False,
        ),
        sa.Column(
            "plan_change_transparency",
            sa.Enum(
                "summary_only",
                "with_reason",
                "full_diff",
                name="interaction_plan_change_transparency",
            ),
            server_default="with_reason",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "interview_sessions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "end_reason",
            sa.Enum(
                "completed", "turn_limit", "early_user", "abandoned", name="interview_end_reason"
            ),
            nullable=True,
        ),
        sa.Column("llm_model", sa.String(length=64), nullable=False),
        sa.Column("total_turns", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("ambiguity_final", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_interview_sessions_user_id"), "interview_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "llm_runs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column(
            "module",
            sa.Enum("interview", "planning", "brief", "recovery", "inbox", name="llm_module"),
            nullable=False,
        ),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("prompt_version", sa.String(length=40), nullable=False),
        sa.Column("input_summary_encrypted", sa.Text(), nullable=True),
        sa.Column("output_summary_encrypted", sa.Text(), nullable=True),
        sa.Column("tokens_in", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("tokens_out", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("latency_ms", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("cost_cents", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("success", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("fell_back", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("trace_id", sa.String(length=60), nullable=True),
        sa.Column("prompt_id", sa.String(length=128), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_llm_runs_created_at"), "llm_runs", ["created_at"], unique=False)
    op.create_index(op.f("ix_llm_runs_trace_id"), "llm_runs", ["trace_id"], unique=False)
    op.create_index(op.f("ix_llm_runs_user_id"), "llm_runs", ["user_id"], unique=False)
    op.create_table(
        "notification_settings",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "morning_brief_time", sa.Time(), server_default=sa.text("'08:00'"), nullable=False
        ),
        sa.Column(
            "evening_reflection_time", sa.Time(), server_default=sa.text("'21:00'"), nullable=False
        ),
        sa.Column(
            "pre_card_enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("push_subscription", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "period_summaries",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "period_type",
            sa.Enum("weekly", "monthly", "quarterly", name="period_type"),
            nullable=False,
        ),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("adherence_rate", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("consistency_days", sa.Integer(), nullable=True),
        sa.Column("resilience_rate", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("avg_delay_minutes", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("drain_point_window", sa.String(length=40), nullable=True),
        sa.Column("peak_point_window", sa.String(length=40), nullable=True),
        sa.Column(
            "category_success_rate",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("restart_success_rate", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("repeated_failure_count", sa.Integer(), nullable=True),
        sa.Column("average_recovery_minutes", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("llm_one_liner", sa.Text(), nullable=True),
        sa.Column("failure_analysis", sa.Text(), nullable=True),
        sa.Column(
            "policy_update_candidates",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "period_type", "start_date", name="uq_period_summaries_user_type_start"
        ),
    )
    op.create_index(
        op.f("ix_period_summaries_user_id"), "period_summaries", ["user_id"], unique=False
    )
    op.create_table(
        "policy_snapshots",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "behavioral_profile",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "execution_constraints",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "interaction_style",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "recovery_policy",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum("rule", "llm", "user_manual", name="policy_source"),
            server_default="rule",
            nullable=False,
        ),
        sa.Column("reason_for_update", sa.String(length=200), nullable=True),
        sa.Column("prompt_version", sa.String(length=40), nullable=True),
        sa.Column(
            "valid_from",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "version", name="uq_policy_snapshots_user_version"),
    )
    op.create_index(
        op.f("ix_policy_snapshots_user_id"), "policy_snapshots", ["user_id"], unique=False
    )
    op.create_table(
        "time_policies",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "policy_type",
            sa.Enum(
                "sleep",
                "lunch",
                "break_min",
                "no_touch",
                "late_night_block",
                "custom",
                name="time_policy_type",
            ),
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_time_policies_user_id"), "time_policies", ["user_id"], unique=False)
    op.create_table(
        "goal_nodes",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("goal_id", sa.UUID(), nullable=False),
        sa.Column("parent_node_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column(
            "node_type",
            sa.Enum("core", "subgoal", "milestone", "leaf", name="goal_node_type"),
            server_default="subgoal",
            nullable=False,
        ),
        sa.Column("depth", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("order_index", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("is_leaf", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["goal_id"], ["goals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_node_id"], ["goal_nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_goal_nodes_goal_id"), "goal_nodes", ["goal_id"], unique=False)
    op.create_index(
        op.f("ix_goal_nodes_parent_node_id"), "goal_nodes", ["parent_node_id"], unique=False
    )
    op.create_table(
        "habit_instances",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("habit_id", sa.UUID(), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("target_count", sa.Integer(), nullable=False),
        sa.Column("done_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["habit_id"], ["habits.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("habit_id", "week_start", name="uq_habit_instances_habit_week"),
    )
    op.create_index(
        op.f("ix_habit_instances_habit_id"), "habit_instances", ["habit_id"], unique=False
    )
    op.create_table(
        "inbox_items",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("raw_text_encrypted", sa.Text(), nullable=False),
        sa.Column(
            "ai_category_guess",
            sa.Enum(
                "study", "project", "health", "routine", "schedule", "other", name="inbox_category"
            ),
            nullable=True,
        ),
        sa.Column(
            "user_category",
            sa.Enum(
                "study", "project", "health", "routine", "schedule", "other", name="inbox_category"
            ),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum("captured", "classified", "archived", "promoted", name="inbox_status"),
            server_default="captured",
            nullable=False,
        ),
        sa.Column("promoted_goal_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["promoted_goal_id"], ["goals.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_inbox_items_user_id"), "inbox_items", ["user_id"], unique=False)
    op.create_table(
        "interview_slot_answers",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("slot_key", sa.String(length=128), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("clarity_score", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["session_id"], ["interview_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "session_id", "slot_key", name="uq_interview_slot_answers_session_slot"
        ),
    )
    op.create_index(
        op.f("ix_interview_slot_answers_session_id"),
        "interview_slot_answers",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "action_items",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=False),
        sa.Column("estimated_minutes", sa.Integer(), server_default=sa.text("30"), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "planned",
                "in_progress",
                "done",
                "partial_done",
                "failed",
                "over_done",
                "archived",
                name="action_status",
            ),
            server_default="planned",
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "goal",
                "habit",
                "inbox",
                "manual",
                "recovery_downscope",
                "recovery_reschedule",
                "recovery_carryover",
                "recovery_park",
                name="action_source",
            ),
            server_default="manual",
            nullable=False,
        ),
        sa.Column("goal_id", sa.UUID(), nullable=True),
        sa.Column("goal_node_id", sa.UUID(), nullable=True),
        sa.Column("habit_instance_id", sa.UUID(), nullable=True),
        sa.Column("habit_id", sa.UUID(), nullable=True),
        sa.Column("inbox_item_id", sa.UUID(), nullable=True),
        sa.Column("parent_action_item_id", sa.UUID(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "study",
                "project",
                "health",
                "routine",
                "schedule",
                "career",
                "relationship",
                "self_dev",
                "other",
                name="action_category",
            ),
            server_default="other",
            nullable=False,
        ),
        sa.Column("why_now", sa.Text(), nullable=True),
        sa.Column("first_step", sa.Text(), nullable=True),
        sa.Column("priority", sa.Integer(), server_default=sa.text("3"), nullable=False),
        sa.Column("system_failure_reason", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["goal_id"], ["goals.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["goal_node_id"], ["goal_nodes.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["habit_id"], ["habits.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["habit_instance_id"], ["habit_instances.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["inbox_item_id"], ["inbox_items.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["parent_action_item_id"], ["action_items.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_action_items_goal_id"), "action_items", ["goal_id"], unique=False)
    op.create_index(op.f("ix_action_items_habit_id"), "action_items", ["habit_id"], unique=False)
    op.create_index(
        op.f("ix_action_items_habit_instance_id"),
        "action_items",
        ["habit_instance_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_action_items_target_date"), "action_items", ["target_date"], unique=False
    )
    op.create_index(op.f("ix_action_items_user_id"), "action_items", ["user_id"], unique=False)
    op.create_table(
        "daily_briefs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("brief_date", sa.Date(), nullable=False),
        sa.Column("headline_text", sa.Text(), nullable=False),
        sa.Column("big_rock_action_item_id", sa.UUID(), nullable=True),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("llm_run_id", sa.UUID(), nullable=True),
        sa.Column("fallback_used", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "adjustment_hints",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["big_rock_action_item_id"], ["action_items.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["llm_run_id"], ["llm_runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "brief_date", name="uq_daily_briefs_user_date"),
    )
    op.create_index(
        op.f("ix_daily_briefs_brief_date"), "daily_briefs", ["brief_date"], unique=False
    )
    op.create_index(op.f("ix_daily_briefs_user_id"), "daily_briefs", ["user_id"], unique=False)
    op.create_table(
        "dependency_links",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("action_item_id", sa.UUID(), nullable=False),
        sa.Column("depends_on_action_item_id", sa.UUID(), nullable=False),
        sa.Column(
            "dependency_type",
            sa.Enum("must_finish", "should_finish", "soft", name="dependency_type"),
            server_default="should_finish",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "action_item_id <> depends_on_action_item_id", name="ck_dependency_links_no_self"
        ),
        sa.ForeignKeyConstraint(["action_item_id"], ["action_items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["depends_on_action_item_id"], ["action_items.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "action_item_id", "depends_on_action_item_id", name="uq_dependency_links_pair"
        ),
    )
    op.create_index(
        op.f("ix_dependency_links_action_item_id"),
        "dependency_links",
        ["action_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dependency_links_depends_on_action_item_id"),
        "dependency_links",
        ["depends_on_action_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dependency_links_user_id"), "dependency_links", ["user_id"], unique=False
    )
    op.create_table(
        "scheduled_blocks",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("action_item_id", sa.UUID(), nullable=False),
        sa.Column("external_calendar_event_id", sa.String(length=200), nullable=True),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "block_status",
            sa.Enum("scheduled", "started", "finished", "cancelled", name="block_status"),
            server_default="scheduled",
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum("ai_plan", "user_edit", "recovery", name="block_source"),
            server_default="ai_plan",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["action_item_id"], ["action_items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scheduled_blocks_action_item_id"),
        "scheduled_blocks",
        ["action_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scheduled_blocks_start_at"), "scheduled_blocks", ["start_at"], unique=False
    )
    op.create_index(
        op.f("ix_scheduled_blocks_user_id"), "scheduled_blocks", ["user_id"], unique=False
    )
    op.create_table(
        "execution_events",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("action_item_id", sa.UUID(), nullable=False),
        sa.Column("scheduled_block_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("plan_start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("plan_end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actual_start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_duration_minutes", sa.Integer(), nullable=True),
        sa.Column("pause_total_minutes", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("delay_minutes", sa.Integer(), nullable=True),
        sa.Column(
            "completion_status",
            sa.Enum(
                "in_progress",
                "done",
                "partial_done",
                "failed",
                "over_done",
                name="execution_completion_status",
            ),
            server_default="in_progress",
            nullable=False,
        ),
        sa.Column("user_rating", sa.Integer(), nullable=True),
        sa.Column("user_feedback_encrypted", sa.Text(), nullable=True),
        sa.Column("focus_mode_used", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("dnd_used", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["action_item_id"], ["action_items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["scheduled_block_id"], ["scheduled_blocks.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_execution_events_action_item_id"),
        "execution_events",
        ["action_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_execution_events_scheduled_block_id"),
        "execution_events",
        ["scheduled_block_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_execution_events_user_id"), "execution_events", ["user_id"], unique=False
    )
    op.create_table(
        "context_snapshots",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("execution_id", sa.UUID(), nullable=False),
        sa.Column(
            "time_of_day",
            sa.Enum(
                "early_morning",
                "morning",
                "afternoon",
                "evening",
                "night",
                name="context_time_of_day",
            ),
            nullable=False,
        ),
        sa.Column(
            "day_of_week",
            sa.Enum("mon", "tue", "wed", "thu", "fri", "sat", "sun", name="context_day_of_week"),
            nullable=False,
        ),
        sa.Column("calendar_density", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("next_event_gap_minutes", sa.Integer(), nullable=True),
        sa.Column("estimated_energy_level", sa.SmallInteger(), nullable=True),
        sa.Column("focus_level", sa.SmallInteger(), nullable=True),
        sa.Column("overwhelm_level", sa.SmallInteger(), nullable=True),
        sa.Column("noise_level", sa.SmallInteger(), nullable=True),
        sa.Column("interruption_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "location_type",
            sa.Enum(
                "home",
                "cafe",
                "library",
                "school",
                "office",
                "transit",
                "etc",
                name="context_location_type",
            ),
            nullable=True,
        ),
        sa.Column(
            "device_type",
            sa.Enum("mobile", "desktop", "tablet", name="context_device_type"),
            nullable=True,
        ),
        sa.Column("weather_info", sa.String(length=50), nullable=True),
        sa.Column("companion_present", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["execution_id"], ["execution_events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_context_snapshots_execution_id"),
        "context_snapshots",
        ["execution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_context_snapshots_user_id"), "context_snapshots", ["user_id"], unique=False
    )
    op.create_table(
        "execution_failure_tags",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("execution_id", sa.UUID(), nullable=False),
        sa.Column("tag_code", sa.String(length=30), nullable=False),
        sa.Column("memo_encrypted", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["execution_id"], ["execution_events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["tag_code"], ["failure_reason_tags.tag_code"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("execution_id", "tag_code", name="uq_execution_failure_tags_event_tag"),
    )
    op.create_index(
        op.f("ix_execution_failure_tags_execution_id"),
        "execution_failure_tags",
        ["execution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_execution_failure_tags_tag_code"),
        "execution_failure_tags",
        ["tag_code"],
        unique=False,
    )
    op.create_table(
        "interruption_events",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("execution_id", sa.UUID(), nullable=False),
        sa.Column(
            "interruption_type",
            sa.Enum(
                "user_pause",
                "external_alert",
                "timer_break",
                "forced_stop",
                name="interruption_type",
            ),
            server_default="user_pause",
            nullable=False,
        ),
        sa.Column(
            "interruption_source",
            sa.Enum(
                "phone",
                "message",
                "person",
                "self_distraction",
                "notification",
                "emergency",
                name="interruption_source",
            ),
            nullable=True,
        ),
        sa.Column("suspended_step", sa.String(length=200), nullable=True),
        sa.Column("resume_delay_minutes", sa.Integer(), nullable=True),
        sa.Column("resumed_after_interrupt", sa.Boolean(), nullable=True),
        sa.Column("interrupt_context_note_encrypted", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["execution_id"], ["execution_events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_interruption_events_execution_id"),
        "interruption_events",
        ["execution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interruption_events_user_id"), "interruption_events", ["user_id"], unique=False
    )
    op.create_table(
        "recovery_attempts",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("execution_id", sa.UUID(), nullable=False),
        sa.Column("trigger_tag", sa.String(length=30), nullable=True),
        sa.Column(
            "recovery_option_group",
            sa.Enum("DOWNSCOPE", "RESCHEDULE", "CARRY_OVER", "PARK", name="recovery_option_group"),
            nullable=False,
        ),
        sa.Column("recovery_strategy_type", sa.String(length=30), nullable=False),
        sa.Column("suggested_action_text", sa.Text(), nullable=True),
        sa.Column(
            "user_decision",
            sa.Enum(
                "pending",
                "accepted",
                "rejected",
                "edited",
                "skipped",
                name="recovery_user_decision",
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("decision_reason", sa.String(length=200), nullable=True),
        sa.Column("recovery_decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("recovery_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("recovery_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("recovery_duration_minutes", sa.Integer(), nullable=True),
        sa.Column(
            "recovery_result",
            sa.Enum("completed", "abandoned", "pending", name="recovery_result"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("resulting_action_item_id", sa.UUID(), nullable=True),
        sa.Column(
            "llm_fallback_used", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["execution_id"], ["execution_events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["recovery_strategy_type"],
            ["recovery_strategy_catalog.strategy_type"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["resulting_action_item_id"], ["action_items.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recovery_attempts_execution_id"),
        "recovery_attempts",
        ["execution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recovery_attempts_recovery_strategy_type"),
        "recovery_attempts",
        ["recovery_strategy_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recovery_attempts_user_id"), "recovery_attempts", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_recovery_attempts_user_id"), table_name="recovery_attempts")
    op.drop_index(
        op.f("ix_recovery_attempts_recovery_strategy_type"), table_name="recovery_attempts"
    )
    op.drop_index(op.f("ix_recovery_attempts_execution_id"), table_name="recovery_attempts")
    op.drop_table("recovery_attempts")
    op.drop_index(op.f("ix_interruption_events_user_id"), table_name="interruption_events")
    op.drop_index(op.f("ix_interruption_events_execution_id"), table_name="interruption_events")
    op.drop_table("interruption_events")
    op.drop_index(op.f("ix_execution_failure_tags_tag_code"), table_name="execution_failure_tags")
    op.drop_index(
        op.f("ix_execution_failure_tags_execution_id"), table_name="execution_failure_tags"
    )
    op.drop_table("execution_failure_tags")
    op.drop_index(op.f("ix_context_snapshots_user_id"), table_name="context_snapshots")
    op.drop_index(op.f("ix_context_snapshots_execution_id"), table_name="context_snapshots")
    op.drop_table("context_snapshots")
    op.drop_index(op.f("ix_execution_events_user_id"), table_name="execution_events")
    op.drop_index(op.f("ix_execution_events_scheduled_block_id"), table_name="execution_events")
    op.drop_index(op.f("ix_execution_events_action_item_id"), table_name="execution_events")
    op.drop_table("execution_events")
    op.drop_index(op.f("ix_scheduled_blocks_user_id"), table_name="scheduled_blocks")
    op.drop_index(op.f("ix_scheduled_blocks_start_at"), table_name="scheduled_blocks")
    op.drop_index(op.f("ix_scheduled_blocks_action_item_id"), table_name="scheduled_blocks")
    op.drop_table("scheduled_blocks")
    op.drop_index(op.f("ix_dependency_links_user_id"), table_name="dependency_links")
    op.drop_index(
        op.f("ix_dependency_links_depends_on_action_item_id"), table_name="dependency_links"
    )
    op.drop_index(op.f("ix_dependency_links_action_item_id"), table_name="dependency_links")
    op.drop_table("dependency_links")
    op.drop_index(op.f("ix_daily_briefs_user_id"), table_name="daily_briefs")
    op.drop_index(op.f("ix_daily_briefs_brief_date"), table_name="daily_briefs")
    op.drop_table("daily_briefs")
    op.drop_index(op.f("ix_action_items_user_id"), table_name="action_items")
    op.drop_index(op.f("ix_action_items_target_date"), table_name="action_items")
    op.drop_index(op.f("ix_action_items_habit_instance_id"), table_name="action_items")
    op.drop_index(op.f("ix_action_items_habit_id"), table_name="action_items")
    op.drop_index(op.f("ix_action_items_goal_id"), table_name="action_items")
    op.drop_table("action_items")
    op.drop_index(op.f("ix_interview_slot_answers_session_id"), table_name="interview_slot_answers")
    op.drop_table("interview_slot_answers")
    op.drop_index(op.f("ix_inbox_items_user_id"), table_name="inbox_items")
    op.drop_table("inbox_items")
    op.drop_index(op.f("ix_habit_instances_habit_id"), table_name="habit_instances")
    op.drop_table("habit_instances")
    op.drop_index(op.f("ix_goal_nodes_parent_node_id"), table_name="goal_nodes")
    op.drop_index(op.f("ix_goal_nodes_goal_id"), table_name="goal_nodes")
    op.drop_table("goal_nodes")
    op.drop_index(op.f("ix_time_policies_user_id"), table_name="time_policies")
    op.drop_table("time_policies")
    op.drop_index(op.f("ix_policy_snapshots_user_id"), table_name="policy_snapshots")
    op.drop_table("policy_snapshots")
    op.drop_index(op.f("ix_period_summaries_user_id"), table_name="period_summaries")
    op.drop_table("period_summaries")
    op.drop_table("notification_settings")
    op.drop_index(op.f("ix_llm_runs_user_id"), table_name="llm_runs")
    op.drop_index(op.f("ix_llm_runs_trace_id"), table_name="llm_runs")
    op.drop_index(op.f("ix_llm_runs_created_at"), table_name="llm_runs")
    op.drop_table("llm_runs")
    op.drop_index(op.f("ix_interview_sessions_user_id"), table_name="interview_sessions")
    op.drop_table("interview_sessions")
    op.drop_table("interaction_styles")
    op.drop_index(op.f("ix_idempotency_keys_user_id"), table_name="idempotency_keys")
    op.drop_index(op.f("ix_idempotency_keys_expires_at"), table_name="idempotency_keys")
    op.drop_table("idempotency_keys")
    op.drop_index(op.f("ix_habits_user_id"), table_name="habits")
    op.drop_table("habits")
    op.drop_index(op.f("ix_goals_user_id"), table_name="goals")
    op.drop_table("goals")
    op.drop_index(op.f("ix_fixed_schedules_user_id"), table_name="fixed_schedules")
    op.drop_table("fixed_schedules")
    op.drop_table("calendar_connections")
    op.drop_table("behavioral_profiles")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("recovery_strategy_catalog")
    op.drop_table("failure_reason_tags")
    # ### end Alembic commands ###

    # PostgreSQL ENUM 타입 수동 drop (Alembic autogenerate 가 자동 안 함).
    for enum_name in (
        "llm_module",
        "policy_source",
        "period_type",
        "recovery_result",
        "recovery_user_decision",
        "recovery_option_group",
        "interruption_source",
        "interruption_type",
        "context_day_of_week",
        "context_device_type",
        "context_location_type",
        "context_time_of_day",
        "execution_completion_status",
        "dependency_type",
        "block_source",
        "block_status",
        "action_source",
        "action_status",
        "action_category",
        "inbox_status",
        "inbox_category",
        "habit_penalty_decision",
        "habit_time_preference",
        "habit_category",
        "goal_status",
        "goal_node_type",
        "goal_tier",
        "goal_category",
        "time_policy_type",
        "calendar_provider",
        "behavioral_recovery_speed",
        "behavioral_energy_cycle",
        "interaction_plan_change_transparency",
        "interaction_reminder_frequency",
        "interaction_explanation_depth",
        "interaction_recovery_tone",
        "interaction_suggestion_style",
        "interview_end_reason",
        "user_tone_mode",
        "user_onboarding_state",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
