"""create user and onboarding tables (2-b)

Revision ID: 9f7c7958ccc8
Revises:
Create Date: 2026-05-21 20:48:00.749836

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9f7c7958ccc8"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column(
            "onboarding_state",
            sa.Enum(
                "WELCOME",
                "ONBOARDING_INTERVIEW",
                "ONBOARDING_CONFIRM",
                "ONBOARDING_CALENDAR",
                "ONBOARDING_MANUAL_SCHEDULE",
                "ONBOARDING_POLICIES",
                "ONBOARDING_FIRST_PLAN",
                "ONBOARDING_NOTIFICATIONS",
                "ACTIVE",
                name="user_onboarding_state",
            ),
            server_default="WELCOME",
            nullable=False,
        ),
        sa.Column(
            "tone_mode",
            sa.Enum("gentle", "strict", "encouraging", name="user_tone_mode"),
            nullable=True,
        ),
        sa.Column("is_beta", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("timezone", sa.String(length=64), server_default="Asia/Seoul", nullable=False),
        sa.Column(
            "last_active_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("anonymized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("focus_mode_preferences", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "behavioral_profiles",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("attention_span", sa.Integer(), server_default=sa.text("30"), nullable=False),
        sa.Column(
            "energy_cycle",
            sa.Enum(
                "morning",
                "afternoon",
                "evening",
                "night",
                "variable",
                name="behavioral_energy_cycle",
            ),
            server_default="variable",
            nullable=False,
        ),
        sa.Column(
            "time_chunk_preference", sa.Integer(), server_default=sa.text("30"), nullable=False
        ),
        sa.Column("success_buffer", sa.Float(), server_default=sa.text("0.2"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "calendar_connections",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("access_token_encrypted", sa.String(length=2048), nullable=False),
        sa.Column("refresh_token_encrypted", sa.String(length=2048), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scope", sa.String(length=512), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "fixed_schedules",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("days_of_week", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_fixed_schedules_user_id"), "fixed_schedules", ["user_id"], unique=False
    )
    op.create_table(
        "interaction_styles",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "suggestion_style",
            sa.Enum("soft", "neutral", "firm", name="interaction_suggestion_style"),
            server_default="neutral",
            nullable=False,
        ),
        sa.Column(
            "recovery_tone",
            sa.Enum("gentle", "normal", "encouraging", name="interaction_recovery_tone"),
            server_default="normal",
            nullable=False,
        ),
        sa.Column(
            "explanation_depth",
            sa.Enum("short", "medium", "detailed", name="interaction_explanation_depth"),
            server_default="medium",
            nullable=False,
        ),
        sa.Column(
            "reminder_frequency",
            sa.Enum("low", "medium", "high", name="interaction_reminder_frequency"),
            server_default="medium",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "interview_sessions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "end_reason",
            sa.Enum("completed", "turn_limit", "early_user", name="interview_end_reason"),
            nullable=True,
        ),
        sa.Column("llm_model", sa.String(length=64), nullable=False),
        sa.Column("total_turns", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("ambiguity_final", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_interview_sessions_user_id"), "interview_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "notification_settings",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "morning_brief_time", sa.Time(), server_default=sa.text("'08:00'"), nullable=False
        ),
        sa.Column(
            "evening_reflection_time", sa.Time(), server_default=sa.text("'21:00'"), nullable=False
        ),
        sa.Column(
            "pre_card_enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("push_subscription", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "interview_slot_answers",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("slot_key", sa.String(length=128), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("clarity_score", sa.Float(), nullable=False),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["session_id"], ["interview_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "session_id", "slot_key", name="uq_interview_slot_answers_session_slot"
        ),
    )
    op.create_index(
        op.f("ix_interview_slot_answers_session_id"),
        "interview_slot_answers",
        ["session_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_interview_slot_answers_session_id"), table_name="interview_slot_answers")
    op.drop_table("interview_slot_answers")
    op.drop_table("notification_settings")
    op.drop_index(op.f("ix_interview_sessions_user_id"), table_name="interview_sessions")
    op.drop_table("interview_sessions")
    op.drop_table("interaction_styles")
    op.drop_index(op.f("ix_fixed_schedules_user_id"), table_name="fixed_schedules")
    op.drop_table("fixed_schedules")
    op.drop_table("calendar_connections")
    op.drop_table("behavioral_profiles")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###

    # Alembic autogenerate가 PostgreSQL ENUM 타입은 자동 drop 하지 않음 — 수동 정리.
    for enum_name in (
        "user_onboarding_state",
        "user_tone_mode",
        "behavioral_energy_cycle",
        "interaction_suggestion_style",
        "interaction_recovery_tone",
        "interaction_explanation_depth",
        "interaction_reminder_frequency",
        "interview_end_reason",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
