"""create planning domain tables (2-c)

Revision ID: ced84c31fc05
Revises: 9f7c7958ccc8
Create Date: 2026-05-21 21:00:05.509115

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ced84c31fc05"
down_revision: str | Sequence[str] | None = "9f7c7958ccc8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "goals",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "study",
                "project",
                "health",
                "routine",
                "schedule",
                "career",
                "relationship",
                "self_dev",
                "other",
                name="goal_category",
            ),
            server_default="other",
            nullable=False,
        ),
        sa.Column(
            "goal_tier",
            sa.Enum("focus", "maintain", "parked", name="goal_tier"),
            server_default="maintain",
            nullable=False,
        ),
        sa.Column("deadline", sa.Date(), nullable=True),
        sa.Column("priority", sa.Integer(), server_default=sa.text("3"), nullable=False),
        sa.Column("why_now", sa.Text(), nullable=True),
        sa.Column("first_step", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_goals_user_id"), "goals", ["user_id"], unique=False)
    op.create_table(
        "habits",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "study",
                "health",
                "routine",
                "self_dev",
                "relationship",
                "other",
                name="habit_category",
            ),
            server_default="other",
            nullable=False,
        ),
        sa.Column("frequency_per_week", sa.Integer(), server_default=sa.text("3"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("frequency_per_week BETWEEN 1 AND 7", name="ck_habit_frequency_range"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_habits_user_id"), "habits", ["user_id"], unique=False)
    op.create_table(
        "inbox_items",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "study", "project", "health", "routine", "schedule", "other", name="inbox_category"
            ),
            server_default="other",
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("captured", "triaged", "archived", name="inbox_status"),
            server_default="captured",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_inbox_items_user_id"), "inbox_items", ["user_id"], unique=False)
    op.create_table(
        "time_policies",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "policy_type",
            sa.Enum(
                "sleep",
                "lunch",
                "break_min",
                "no_touch",
                "late_night_block",
                "custom",
                name="time_policy_type",
            ),
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_time_policies_user_id"), "time_policies", ["user_id"], unique=False)
    op.create_table(
        "action_items",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=False),
        sa.Column("estimated_minutes", sa.Integer(), server_default=sa.text("30"), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "planned",
                "in_progress",
                "done",
                "partial_done",
                "failed",
                "over_done",
                "archived",
                name="action_status",
            ),
            server_default="planned",
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum("goal", "habit", "inbox", "manual", "recovery", name="action_source"),
            server_default="manual",
            nullable=False,
        ),
        sa.Column("goal_id", sa.UUID(), nullable=True),
        sa.Column("habit_id", sa.UUID(), nullable=True),
        sa.Column("inbox_item_id", sa.UUID(), nullable=True),
        sa.Column("parent_action_item_id", sa.UUID(), nullable=True),
        sa.Column("why_now", sa.Text(), nullable=True),
        sa.Column("first_step", sa.Text(), nullable=True),
        sa.Column("priority", sa.Integer(), server_default=sa.text("3"), nullable=False),
        sa.Column("system_failure_reason", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["goal_id"], ["goals.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["habit_id"], ["habits.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["inbox_item_id"], ["inbox_items.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["parent_action_item_id"], ["action_items.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_action_items_goal_id"), "action_items", ["goal_id"], unique=False)
    op.create_index(op.f("ix_action_items_habit_id"), "action_items", ["habit_id"], unique=False)
    op.create_index(
        op.f("ix_action_items_target_date"), "action_items", ["target_date"], unique=False
    )
    op.create_index(op.f("ix_action_items_user_id"), "action_items", ["user_id"], unique=False)
    op.create_table(
        "goal_nodes",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("goal_id", sa.UUID(), nullable=False),
        sa.Column("parent_node_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("depth", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["goal_id"], ["goals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_node_id"], ["goal_nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_goal_nodes_goal_id"), "goal_nodes", ["goal_id"], unique=False)
    op.create_index(
        op.f("ix_goal_nodes_parent_node_id"), "goal_nodes", ["parent_node_id"], unique=False
    )
    op.create_table(
        "habit_instances",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("habit_id", sa.UUID(), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("target_count", sa.Integer(), nullable=False),
        sa.Column("done_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["habit_id"], ["habits.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("habit_id", "week_start", name="uq_habit_instances_habit_week"),
    )
    op.create_index(
        op.f("ix_habit_instances_habit_id"), "habit_instances", ["habit_id"], unique=False
    )
    op.create_table(
        "dependency_links",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("predecessor_action_item_id", sa.UUID(), nullable=False),
        sa.Column("successor_action_item_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "predecessor_action_item_id <> successor_action_item_id",
            name="ck_dependency_links_no_self",
        ),
        sa.ForeignKeyConstraint(
            ["predecessor_action_item_id"], ["action_items.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["successor_action_item_id"], ["action_items.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "predecessor_action_item_id",
            "successor_action_item_id",
            name="uq_dependency_links_pair",
        ),
    )
    op.create_index(
        op.f("ix_dependency_links_predecessor_action_item_id"),
        "dependency_links",
        ["predecessor_action_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dependency_links_successor_action_item_id"),
        "dependency_links",
        ["successor_action_item_id"],
        unique=False,
    )
    op.create_table(
        "scheduled_blocks",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("action_item_id", sa.UUID(), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "block_status",
            sa.Enum("scheduled", "completed", "cancelled", name="block_status"),
            server_default="scheduled",
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum("ai_plan", "user_edit", "recovery", "manual", name="block_source"),
            server_default="ai_plan",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["action_item_id"], ["action_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scheduled_blocks_action_item_id"),
        "scheduled_blocks",
        ["action_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scheduled_blocks_start_at"), "scheduled_blocks", ["start_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scheduled_blocks_start_at"), table_name="scheduled_blocks")
    op.drop_index(op.f("ix_scheduled_blocks_action_item_id"), table_name="scheduled_blocks")
    op.drop_table("scheduled_blocks")
    op.drop_index(
        op.f("ix_dependency_links_successor_action_item_id"), table_name="dependency_links"
    )
    op.drop_index(
        op.f("ix_dependency_links_predecessor_action_item_id"), table_name="dependency_links"
    )
    op.drop_table("dependency_links")
    op.drop_index(op.f("ix_habit_instances_habit_id"), table_name="habit_instances")
    op.drop_table("habit_instances")
    op.drop_index(op.f("ix_goal_nodes_parent_node_id"), table_name="goal_nodes")
    op.drop_index(op.f("ix_goal_nodes_goal_id"), table_name="goal_nodes")
    op.drop_table("goal_nodes")
    op.drop_index(op.f("ix_action_items_user_id"), table_name="action_items")
    op.drop_index(op.f("ix_action_items_target_date"), table_name="action_items")
    op.drop_index(op.f("ix_action_items_habit_id"), table_name="action_items")
    op.drop_index(op.f("ix_action_items_goal_id"), table_name="action_items")
    op.drop_table("action_items")
    op.drop_index(op.f("ix_time_policies_user_id"), table_name="time_policies")
    op.drop_table("time_policies")
    op.drop_index(op.f("ix_inbox_items_user_id"), table_name="inbox_items")
    op.drop_table("inbox_items")
    op.drop_index(op.f("ix_habits_user_id"), table_name="habits")
    op.drop_table("habits")
    op.drop_index(op.f("ix_goals_user_id"), table_name="goals")
    op.drop_table("goals")
    # ### end Alembic commands ###

    # PostgreSQL ENUM 타입 수동 drop (Alembic autogenerate 가 자동 안 함).
    for enum_name in (
        "block_source",
        "block_status",
        "action_source",
        "action_status",
        "inbox_status",
        "inbox_category",
        "habit_category",
        "goal_tier",
        "goal_category",
        "time_policy_type",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
